version: '3.3'
services:
  server:
    build: .
    environment:
      RAILS_ENV: 'development'
    ports:
      - '3000:3000'
    volumes:
    - .:/code

# docker-compose -f docker-compose.dev.yml up --build