# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3eff43cc94fd6470445f523d3f74ca59a10eab5efd64135d3db0bbb823a7084251b45cccab6ed5f14697dc2bd88b7d7ad5a8be035aaf9a59a39f993e71a3c5

test:
  secret_key_base: 7f4b184c3a21a5ade4d2032b1415b9ed636b7a0cb7ec203f3e6d932717d932665c6137ef045a94801f659872e20e2d26a6de8be63f6b00594741d6a1dc003de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
